name: maintenance_config
description: Dart starter for Appwrite function.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: "^3.0.0"

dependencies:
  yaml: ^3.1.1
  dart_appwrite: ^10.0.0
  equatable: ^2.0.5
  intl: ^0.19.0
      
dev_dependencies:
  lints: ^2.0.1
